name: ops_monitoring

services:
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - monitoring
    restart: always
    container_name: prometheus
    logging:
      driver: json-file
      options:
        labels: "container_name,container_id"
        tag: "{{.Name}}/{{.ID}}"

  grafana:
    image: grafana/grafana-enterprise
    ports:
      - "80:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - .env  
    networks:
      - monitoring
    restart: always
    container_name: grafana
    logging:
      driver: json-file
      options:
        labels: "container_name,container_id"
        tag: "{{.Name}}/{{.ID}}"


networks:
  monitoring:
    driver: bridge

volumes:
  grafana-storage:
    driver: local
